### PR TITLE
Reuse a config in memory if a dashboard doesn‘t have a config

### PR DESCRIPTION
**Pull request by elchininet**
This pull request refactors the configuration retrieval logic to do the same:

1. When a dashboard is loaded, if it has a config it is loaded in memory (same as before)
2. When a dashboard is loaded, if it doesn‘t have a config it checks if there is a config in memory and if that is the case it reuses that config
3. When a dashboard is loaded, if it doesn‘t have a config and there is no config in memory it initiates an empty config (same as before)

As part of this merge request also a new `debug` parameter has been added to the configuration:

```yaml
custom_attributes:
  debug: true
```

If this parameter is `true`, every time that the plugin performs an action it is printed in the console:

### Case 1 (config exists)

image

### Case 2 (config doesn‘t exist but there is a config in memory)

image

### Case 3 (config doesn‘t exist and there is no config in memory)

It should not be printed, if it happens something weird has occur

### Dialog has been opened

image

### CODE REVIEW

**Comment by Mariusthvdb** [comment]
[besides the point of the empty printed filters in the inspector,](https://github.com/Mariusthvdb/custom-attributes/issues/33#issuecomment-1857531053) this seems to work correctly now, and all filters are applied.

if you are ready for it please merge? you are in the lead on this one, so I wont interfere.

**Comment by elchininet** [comment]
I did a small change:

1. We used a cached version of the filters if they are found in memory, but this action didn‘t have a debug message, I have added one there

2. If the debug message contains an object, it is printed as `JSON` to avoid some developer tools to hide its content.

image

**Comment by Mariusthvdb** [comment]
do we still need the other 2 PR's now, or are they superseded with this

**Comment by elchininet** [comment]
Only one of those is still needed, first let's try #35, if you test it and you find some issue there then we go with #32 (letting the list array in the code and just maintain it adding more elements if some failing entities are reported).

**Comment by Mariusthvdb** [comment]
Infra that small change caused the plugin to not work correctly aas before.

Scherm­afbeelding 2023-12-15 om 11 36 04

there is no logging anymore, and I again need to read the view for the filter to work

**Comment by elchininet** [comment]
It should not be related to that change. Just make sure that you are using the right script  That change is applied after the configuration is loaded and after several debug messages. What you should see if it fails is something like "attributes cannot be found", but the missing debug messages are not related to it.

**Comment by elchininet** [comment]
Of course, you nedd to make sure that the first time Home Assistant loads, the dashboard that you are loading has a configuration inside, if there is no configuration at the beginning, there is no configuration to recover from memory and there is no `debug` parameter to start printing messages.

**Comment by Mariusthvdb** [comment]
I dl'ed the latest main, installed and reloaded resources several times. refreshed, all according to the instructions  ;-)


and yet there is the same band behavior as before, requiring a reload of each and every dashboard after changing. Also, there is not a single logging in the inspector mentioning what I screenshotted earlier

**Comment by Mariusthvdb** [comment]
progress....

I killed the browser completely , re-opene empty, cleared cache , and fired up HA, in inspector I now see the 

Scherm­afbeelding 2023-12-15 om 11 53 55


and yes, I do believe the filters are being applied again ... pff

**Comment by elchininet** [comment]
>I killed the browser completely , re-opene empty, cleared cache , and fired up HA, in inspector I now see the

Voilà, good news 👍

**Comment by elchininet** [comment]
>so the filters are now indeed shown where they were not visible before

Super, the `JSON` stringify is capable of bypassing weird developer tools behaviours. 👍

Also, it is more user friendly and less `dev` debug message in that way.

**Comment by Mariusthvdb** [comment]
cool.

2 things:
- i dont understand why I had this issue, and you didnt see it yesterday. I mean, I am glad you were able to fix it with this memory trick (isnt that costly for the system btw), but I still would like to understand why this extra measure is required now, doesnt it feel a bit like a hack?

- what you state here:

> Of course, you need to make sure that the first time Home Assistant loads, the dashboard that you are loading has a configuration inside, if there is no configuration at the beginning, there is no configuration to recover from memory and there is no debug parameter to start printing messages.


  might need some layman translation. I mean, I had not changed my configs, and all dashboard have the same config. Are you in fact saying that we need to reload all dashboards upon each and every HA restart? that would rather a tedious operation not to say very ugly...

Hoping I misunderstand what you're saying here, I would have hoped the Frontend to automatically load the config in its memory, simply because we load the plugin resource and it reads the filtered_attributes configuration at that time

**Comment by elchininet** [comment]
>i dont understand why I had this issue, and you didnt see it yesterday. I mean, I am glad you were able to fix it with this memory trick (isnt that costly for the system btw), but I still would like to understand why this extra measure is required now, doesnt it feel a bit like a hack?

I also don‘t understand why you had the issue, and I didn‘t see it because I am not in your computer, I am just following what you see and later tell me 😉

And no, this is no costly, it is nothing, imagine that the configuration is inside our plugin because we loaded it before, if we reach a dashboard without configuration (for whatever reason) what we was doing was to overwrite the previous configuration with an empty object and then try to continue (and everything will fail because the configuration is empty, no errors, but it will not hide any attribute), it is wise to avoid overriding the config if it is already there, it doesn‘t harm.

>but I still would like to understand why this extra measure is required now, doesnt it feel a bit like a hack?

This is helpful, is not in fact an extra measure, this also allows one to write the config in the main lovelace dasboard that you know that will be loaded when Home Assistant loads and do not add it in the rest, so it will be loaded from memory in those dashboards. So, for those users that are not using `yaml` mode and included yaml files this will be super helpful.

>might need some layman translation. I mean, I had not changed my configs, and all dashboard have the same config. Are you in fact saying that we need to reload all dashboards upon each and every HA restart? that would rather a tedious operation not to say very ugly...

No, what I am saying is that if HA loads and the main dashboard doesn‘t have a `custom_attributes` property, there is no way on earth that this plugin could load a configuration and reuse in the consecuent dashboards because it doesn‘t exist. You need to be sure that when Home Assistant load at least the main dashboard that is loaded in `yourhost:8123/lovelace` has the `custom_attributes` configuration on it, otherwise there is no way to invent it. It means that if you add the configuration in the main lovelace dashboard and start Home Assistant in `yourhost:8123/esphome/ingress`, it will not load any configuration because in that address there is not a lovelace dashboard, so going to a dashboard without config afyer that doesn‘t load the config from memory because it has not beeing loaded yet, you need to go to the panel with the configuration first and then and only then it will be reused in the consecuent dashboards without configuration. Hope that you understand with the long explanation 🙂

>Hoping I misunderstand what you're saying here, I would have hoped the Frontend to automatically load the config in its memory, simply because we load the plugin resource and it reads the filtered_attributes configuration at that time

To load the config from memory, the config should be loaded first from a lovelace dashboard (it is the place that we use to add the configuration), if the plugin cannot load it because it is not included in the first dashboard that was loaded or because the page that is loaded is not a lovelace dashboard, there is no way to read it and therefore there is no way to reuse it later.

**Comment by Mariusthvdb** [comment]
ok lets move forward and see how things develop. so far so good

**Pull request merged**
