### PR TITLE
Query for the first child of the more-info content

### PR DESCRIPTION
**Pull request by elchininet**
At the moment, we are querying for specific element names inside the `more-info-content`, this is not scalable as I am sure that there are a ton of more elements that we have not detected yet. To make the code more future proof, I am removing all the queries for `more-info-default`, `more-info-vacuum`, `more-info-light` and `more-info-siren` and just querying for the element inside the `more-info-content`.

### CODE REVIEW

**Comment by elchininet** [comment]
@Mariusthvdb,
Could you go through all your attributes and check that nothing got broken with this change?
(For the future, end-to-end tests are the response to this as we did in Kiosk-mode)

**Comment by Mariusthvdb** [comment]
I will in a minute...

Does this also see to more-info-group? 
I remember that being a challenge in the original custom-ui.

In the end, that brought about my wish to modernize and update..

**Comment by elchininet** [comment]
>Does this also see to more-info-group?

It should, but now that you mention, the previous code should fail with `more-info-group` because it is not included in the query.

**Comment by elchininet** [comment]
If you can test it on a `more-info-group` it would be great (I don‘t have any of those). If it fails just send me an screenshot of the DOM tree to see how they are built.

**Comment by Mariusthvdb** [comment]
> If you can test it on a `more-info-group` it would be great (I don‘t have any of those). If it fails just send me an screenshot of the DOM tree to see how they are built.

I think I am being misstaken. These we had was with the dropdown event, and hide upon that event. Now we dont do that anymore, I suppose that specific worry isnt necessary anymore.

we will see.

**Comment by Mariusthvdb** [comment]
so I updated, but a not sure it is working as it should be. 

I ws fooled by
```
  by_glob:

    'sensor.buienradar_*':
      - stationname
 ```

and it remained visible. I checked dev tools state again only to see those attributes are in fact capitalized..... which is an oddity. changed the filter and now it is gone.

But, I seem to have to reload the page again and again, as if the filter needs to be re-read after changing a dashboard.

Before this PR, I had to do that after each modification in the filter for every Dashboard. Now it  happens all the time.

So that is definitely not good.

I dont see any errors in inspector

**Comment by elchininet** [comment]
Just send me an screenshot of the DOM tree of those `sensor.buienradar_*` more-info dialogs, maybe there is another element before the proper element, something that would require another approach.

**Comment by Mariusthvdb** [comment]
no, those buienradar attributes actually are capitalized:

Scherm­afbeelding 2023-12-14 om 19 24 12

and since I had it sent initially to filter `stationname` that didnt work. changing it to `Stationname` made the filter kick in.

But....

I just restarted to give it a fresh jump and hopefully clear everything cache needed, it still doesnt work without reloading the view. Upon each view change (so not only Dashboard change as I initially thought ) I need to read it.

We either need to find the reason, or revert the latest PR..

**Comment by Mariusthvdb** [comment]
Scherm­afbeelding 2023-12-14 om 19 39 13

**Comment by elchininet** [comment]
Oh, weird, it is just a normal `more-info-default`. I assume that maybe other element is there before it and then it is picked by the query and that makes sense. I‘ll let then the previous approach just adding a comment to make it easier to fix something in the future.

**Pull request closed without merging**
