### PR TITLE
Implement an "all" filter for the filter_attributes filters

### PR DESCRIPTION
**Pull request by elchininet**
This pull request implements a `all` filter to filter all the attributes from a specific filter parameter. It works with all the filter parameters:

```yaml
custom_attributes:
  filter_attributes:
    by_entity_id:
      binay_sensor.name_of_binary_sensor:
        - all
    by_domain:
      sensor:
        - all
    by_device_class:
      motion:
        - all
    by_glob:
      sensor.garden_*:
        - all
```

### CODE REVIEW

**Comment by elchininet** [comment]
@Mariusthvdb,
It is a small change but it should do the trick. Test it and let me know.

**Comment by Mariusthvdb** [comment]
magic:
before
Scherm­afbeelding 2023-12-14 om 11 23 52

after
Scherm­afbeelding 2023-12-14 om 11 24 46

using:
```
  by_entity_id:

    device_tracker.google_hub_kitchen:
      - all
```

**Comment by elchininet** [comment]
Super, glad that it is working properly.

**Comment by Mariusthvdb** [comment]
I found an issue:

using:
```
filter_attributes:

  by_glob:

    '*.*':
      - icon_color
    device_tracker.google*:
      - all #is_guest

  by_domain:

    binary_sensor:
      - hysteresis

    light:
      - all

    siren:
      - available_tones

  by_device_class:

    enum:
      - options

  by_entity_id:

    sensor.cpu_speed:
      - brand
 ```

the icon_color on the binary_sensor entities is not filtered. all others are but these remain in view

I suppose somehow the order of filters, or hierarchy is troubling me here?

**Pull request merged**
