### PR TITLE
Add a comment for more info children

### PR DESCRIPTION
**Pull request by elchininet**
This pull request moves the elements to query inside the `more-info-content` element to a separate array in the constant file to make it easier to find them and to add more elements to it in the future.

I have added a comment to make it easier for others. If for some reason, in the feature some attributes are not picked by the plugin, first thinf to check is that the element inside the `more-info-content` element is included in the list, if it is not, just adding it to the list should fix the issue (just like [this](https://github.com/Mariusthvdb/custom-attributes/pull/10#issuecomment-1855428744)).

### CODE REVIEW

**Comment by elchininet** [comment]
@Mariusthvdb,
Check the comment and let me know if it understandable what do you need to do if in the future some attributes are not picked and ignored by the plugin.

**Comment by elchininet** [comment]
>eally sorry, but it still doesnt work. Ive installed https://github.com/Mariusthvdb/custom-attributes/commit/92852523e60698e31ce2fbc7afc137c167f7643e now, and see no comments at all.

Ths pull request doesn‘t change anything related to code, it is the same, it just changes the place of an array, so just check that the issue that you are having is just there no matter what and we need to find the root cause.

The comments are located in this pull request, just go to the "Files changed" tab and read the comments.

**Comment by Mariusthvdb** [comment]
your right. I downgraded to the last version before 1.0.0 and it now has the same issue...
only thing that changed meanwhile is a supervisor update.

and I disabled the frontend debug in the settings.

Scherm­afbeelding 2023-12-14 om 21 16 33

other than that I am puzzled.

**Comment by elchininet** [comment]
Weird, just create an issue about this and let‘s discuss it there.

**Comment by elchininet** [comment]
>btw I reenabed the logging, but ofc no difference.

It should not, I have checked and mine is disabled

>wonder if Supervisor has anything to do with it.

It should not, I think.

**Comment by Mariusthvdb** [comment]
> Weird, just create an issue about this and let‘s discuss it there.

done. 
if your confident we can merge, or rather wait for the issue to be fixed?
what do you see locally?

**Comment by elchininet** [comment]
>if your confident we can merge, or rather wait for the issue to be fixed?

Let‘s wait, if it is solved I am more in favor of the previous one that I closed.

>what do you see locally?

Nothing has changed for me, everything is working as before.

**Comment by Mariusthvdb** [comment]
and using this too:

Scherm­afbeelding 2023-12-14 om 22 16 53

**Comment by elchininet** [comment]
I have not updated to `2023.12.2`, let me do it.

**Pull request closed without merging**
