### PR TITLE
Implement configuration

### PR DESCRIPTION
**Pull request by elchininet**
This pull request implements a way to configure how the plugin should behave. To enable the plugin one needs to add the `custom_attributes` parameter to the root of the lovelace yaml file:

```yaml
custom_attributes:
   # Configuration
```

#### filter_attributes

This parameter controls what should be filtered out from the more-info dialogs attributes:

```yaml
custom_attributes:
  filter_attributes:
    # filter_attributes parameters   
```

#### filter_attributes > by_entity_id

This parameter filters attributes from entities matching their `entity_id`, it must contain an array of attributes' names. This parameter will override any other parameter that you add to `filter_attributes`:

```yaml
custom_attributes:
  filter_attributes:
    by_entity_id:
      binay_sensor.name_of_binary_sensor:
        - some_attribute_name
        - some_attribute_name
```

#### filter_attributes > by_domain

This parameter filters attributes from entities matching their domain, it must contain an array of attributes' names. This parameter will override the parameters `by_device_class` and `by_glob`:

```yaml
custom_attributes:
  filter_attributes:
    by_domain:
      sensor:
        - some_attribute_name
        - some_attribute_name
```

#### filter_attributes > by_device_class

This parameter filters attributes from entities matching their device class, it must contain an array of attributes' names. This parameter will override the `by_glob` parameter:

```yaml
custom_attributes:
  filter_attributes:
    by_device_class:
      motion:
        - some_attribute_name
        - some_attribute_name
```

#### filter_attributes > by_glob

This parameter filters attributes from entities matching a glob pattern of their `entity_id`, it must contain an array of attributes' names. This parameter can be overriden by any other parameter in `filter_attributes`:

```yaml
custom_attributes:
  filter_attributes:
    by_glob:
      sensor.garden_*:
        - some_attribute_name
        - some_attribute_name
```

### CODE REVIEW

**Comment by Mariusthvdb** [comment]
thx!
this amazing stuff your pulling!

it seemed to work fine, until I added the by_domain for the siren:
```
filter_attributes:

  by_glob:

    '*.*':
      - icon_color
    device_tracker.google*:
      - is_guest

  by_domain:

    siren:
      - available_tones

  by_device_class:

    enum:
      - options

  by_entity_id:

    sensor.cpu_speed:
      - brand
 ```

and then one of the other filters work anymore either 

Scherm­afbeelding 2023-12-13 om 20 07 30

Scherm­afbeelding 2023-12-13 om 20 07 50


need to have a deeper look.
btw, there are no errors in inspector

**Comment by elchininet** [comment]
Hey @Mariusthvdb,
Describe what happened when you added `by_domain`, which one sopped working?

**Comment by Mariusthvdb** [comment]
all stopped working mysteriously.

commenting the domain glob as follows
```
filter_attributes:

  by_glob:

    '*.*':
      - icon_color
    'device_tracker.google*':
      - is_guest

#   by_domain:
#
#     siren:
#       - available_tones

  by_device_class:

    enum:
      - options

  by_entity_id:

    sensor.cpu_speed:
      - brand
```

makes them work again

if I add the siren as a glob:
```
filter_attributes:

  by_glob:

    '*.*':
      - icon_color
    device_tracker.google*:
      - is_guest

    siren.*:
      - available_tones

#   by_domain:
#
#     siren:
#       - available_tones

  by_device_class:

    enum:
      - options

  by_entity_id:

    sensor.cpu_speed:
      - brand
```

it doesnt work either, so maybe something is going on with that siren domain..

btw, note I also checked the quoting of the globs. they are only required when starting the entity. that still is the same as before, but my tests confirmed it. good to know.

**Comment by elchininet** [comment]
>all stopped working mysteriously.

Let me see if I can find a possible reason for that.

>btw, note I also checked the quoting of the globs. they are only required when starting the entity. that still is the same as before, but my tests confirmed it. good to know.

Yes, it is needed to quote them

>btw2: not mentioned in the PR comments above, but the order of the filters doesnt matter does it?

No, it doesn‘t matter (or it should not).

Let me try to review the code line by line.

**Comment by elchininet** [comment]
@Mariusthvdb,
Test it again and let me know if the `by_domain` filter is fixed.

**Comment by elchininet** [comment]
Oh, I didn‘t see this:

>it doesnt work either, so maybe something is going on with that siren domain..

I need that you do something on your side, open the more-info dialog for the `siren` entity. Right click on the attributes, select in the DOM three the `ha-attributes` element and then in the console write this:

```bash
$0.__stateObj
```

Hit on enter, open all the properties of the object that it prints in the console and take an screenshot.

**Comment by Mariusthvdb** [comment]
```
  by_domain:

    binary_sensor:
      - hysteresis

#     siren:
#       - available_tones

```

the hysteresis attribute gets filtered.
the available_tones does not get filtered.... could it be its because its a tuple, and not a single attribute?

**Comment by elchininet** [comment]
Just take an screenshot with the instructions that I gave you, I need to see what is inside that entity.

**Comment by Mariusthvdb** [comment]
> Oh, I didn‘t see this:
> 
> > it doesnt work either, so maybe something is going on with that siren domain..
> 
> I need that you do something on your side, open the more-info dialog for the `siren` entity. Right click on the attributes, select in the DOM three the `ha-attributes` element and then in the console write this:
> 
> ```shell
> $0.__stateObj
> ```
> 
> Hit on enter, open all the properties of the object that it prints in the console and take an screenshot.

Scherm­afbeelding 2023-12-13 om 23 26 57

**Comment by elchininet** [comment]
Everything seems OK there except the `available_tones`, it is an object but with number indexes (as an `array`). Do something, with the same `ha-attributes` element selected write this an hit enter:

```
$0.extraFilters
```

And check if it prints `available_tones`. I am pretty sure that it is set correctly but for some reason Home Assistant decides to ignore it.

**Comment by Mariusthvdb** [comment]
using the by_domain

```
    siren:
      - available_tones
```

and glob:
```
    siren.*:
      - available_tones
```

and by_entity_id:
```
    siren.alarm:
      - available_tones
```
all show:

Scherm­afbeelding 2023-12-14 om 07 52 43

**Comment by elchininet** [comment]
I think that the issue is something else, take an screenshot of the DOM tree of that more-info dialog (mainly after the content), it seems that siren entities have a different layout so we need to include it to the query (and also in kiosk mode).

**Comment by Mariusthvdb** [comment]
DOM tree of more-info-siren
Scherm­afbeelding 2023-12-14 om 09 46 44

**Comment by elchininet** [comment]
Exactly, `more-info-siren`, we need to include that one in the query, let me do it quickly.

**Comment by Mariusthvdb** [comment]
while you make your miracles work, please let me ask this:
shouldnt there have been some error from this card stating a customization couldnt be set? 

also, please check the date of the release. a terribly minor detail, but it would be cool if we had it right from the first release !

**Comment by elchininet** [comment]
It is already pushed, what happens is that for some reason Home Assistant decided to create a generic `more-info-default` for almost all the more.info dialogs entities but for other it is very specific (`vacuum` and `light` for example) and now we know that also `siren` (more should appear in the future).

**Comment by Mariusthvdb** [comment]
ill test all available domains in the next few hours/days....

bingo!
before:

Scherm­afbeelding 2023-12-14 om 09 57 05


after by_domain:

Scherm­afbeelding 2023-12-14 om 09 57 33

Very nice, the frontend is cleaning up nicely indeed!

now we only 'need' that `all` parameter I guess, so we can clean up your printer and the Google Homes. And probably a whole lot of other entities with those long lists of attributes.

**Comment by Mariusthvdb** [comment]
> It is already pushed, what happens is that for some reason Home Assistant decided to create a generic `more-info-default` for almost all the more.info dialogs entities but for other it is very specific (`vacuum` and `light` for example) and now we know that also `siren` (more should appear in the future).

wouldnt it be best if we merged this now, and continue from there? I am eager to see it published. You can merge too cant you?

**Comment by elchininet** [comment]
>shouldnt there have been some error from this card stating a customization couldnt be set?

Not with more info-dialogs. They are so diferent and some of them don‘t have the same structure at all, so if you throw an error, if it doesn‘t find an element it will be erroing all the time (for example, telling you that it cannot find attributes in a more-info dialog that doesn‘t have attributes or doesn‘t have any of that sctructure, like `updates` for example). So the approach is, "try to find the attributes but if you don‘t find it, it is OK, most probably they are not there", it is not like the header or the sidebar in `kiosk-mode`, if they are not there you know that there is an issue so an error is thrown.

>also, please check the date of the release. a terribly minor detail, but it would be cool if we had it right from the first release !

This is not important at the moment, let‘s make the code work properly with all the features first, those things will come later.

**Comment by elchininet** [comment]
>wouldnt it be best if we merged this now, and continue from there? I am eager to see it published. You can merge too cant you? Feel free to hit that button!

We can do it, but this is a minor thing just to make the configuration work without issues, so when everything is working we can merge it.

**Comment by elchininet** [comment]
>now we only 'need' that all parameter I guess, so we can clean up your printer and the Google Homes. And probably a whole lot of other entities with those long lists of attributes.

This should be in a separate merge request. I‘ll take a look at it.

**Comment by elchininet** [comment]
>Very nice, the frontend is cleaning up nicely indeed!

It seems that it is working then :)

Let‘s merge it then. I‘ll try to focus later in the `all` option (I am thinking that it would be weird that someone named an attribute `all`) and the `unhide` I have an idea to bypass what Home Assistant is doing.

**Pull request merged**
