### PR TITLE
Query for the first child of the more-info content

### PR DESCRIPTION
**Pull request by elchininet**
These changes are the same as the ones applied in #30 

At the moment, we are querying for specific element names inside the `more-info-content`, this is not scalable as I am sure that there are a ton of more elements that we have not detected yet. To make the code more future proof, I am removing all the queries for `more-info-default`, `more-info-vacuum`, `more-info-light` and `more-info-siren` and just querying for the element inside the `more-info-content`.

### CODE REVIEW

**Comment by elchininet** [comment]
@Mariusthvdb,
Let‘s try again with this one, let me know if you find any issues on your side.

**Comment by Mariusthvdb** [comment]
> @Mariusthvdb, Let‘s try again with this one, let me know if you find any issues on your side.

before I do, please see my findings after the Main merge in that PR

**Comment by Mariusthvdb** [comment]
ok let me try this now. Does it also have the new debugging installed like Main has now? I can simply overwrite my current Main version with this?

**Comment by elchininet** [comment]
>ok let me try this now. Does it also have the new debugging installed like Main has now? I can simply overwrite my current Main version with this?

It is just a branch from master, so yes

>well, I cant get it to break ;-) All is working, and I see the correct debug filters being printed

Good to know 👍

>only thing that is a bit ugly is the rendering of the more-info panel itself, which is not very fluent. on power sensors with a graph, its an odd sight to see the panel change proportions during rendering

That is a Home Assistant thing, they animate the more-info dialog, and it seems that in your case the graph is taking a long time to load (I don‘t know why). This plugin is just doing a very fast task that would not take more than a few milliseconds and it is doing it asynchronously, so it should not block the UI. It is not costly in terms of resources, so you should not see any difference in terms of performance disabling or enabling the plugin.

**Comment by Mariusthvdb** [comment]
then please merge, all good?

**Comment by elchininet** [comment]
>then please merge, all good?

Yep, let me close the other PR, it is not needed with this change.

**Pull request merged**
